libraries:
  Movies:
    overlay_files:
      # Creates a ribbon style background in the top left corner with a width of 313 pixels. Keep in mind, it has to be run before any overlay which is supposed to be on top of the background
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/background_top_left_313_wide.yml
      
      # Resolution in the upper left corner in 45 degree format
      - pmm: resolution
        template_variables:
          url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/resolution-top-left-45deg/<<overlay_name>>.png
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          final_horizontal_offset: 0
          final_vertical_offset: 0
          back_width: 1000
          back_height: 1500
          back_color: 00

      # Audio in the upper left corner in 45 degree format
      - pmm: audio_codec
        template_variables:
          url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/audio-top-left-45deg/<<key>>.png
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          back_color: 00

      # Award ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_awards.yml

      # IMDB ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_imdb.yml

      # Rotten tomatoes ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_rotten.yml

      # Trending ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_trending.yml


  TV Shows:
    overlay_files:
      # Status in the top left corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/status.yml

      # Fallback Network logo which is overwritten by pmm: network if it finds an image for the network. Must run before pmm: network.
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network_fallback.yml

      # Uses the default PMM network but replaces the image with custom ones
      - pmm: network
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/<<key>>.png 
          back_color: 00 

  Anime Series:
    overlay_files:
      - pmm: studio
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_align: top
          vertical_offset: 0
          back_width: 1000
          back_height: 1500
          url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/studio-top-left/<<key>>.png
          back_color: 00

  Formula 1:
    metadata_files:
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/formula1.yml
    operations:
      assets_for_all: true 
