libraries:
  Movies:
    overlay_files:
      # Resolution in the upper left corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/resolution.yml

      # Audio in the upper left corner besides resolution
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/audio_codec.yml

      # Award ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_awards.yml

      # IMDB ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_imdb.yml

      # Rotten tomatoes ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_rotten.yml

      # Trending ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon_trending.yml


  TV Shows:
    overlay_files:
      # Status in the top left corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/status.yml

      # Fallback Network logo which is overwritten by pmm: network if it finds an image for the network. Must run before pmm: network.
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network_fallback.yml

      # Uses the default PMM network but replaces the image with custom ones
      - pmm: network
        template_variables:
          horizontal_align: left
          horizontal_offset: 0
          vertical_offset: 0
          vertical_align: top
          back_width: 1000
          back_height: 1500
          url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/network-top-left/<<key>>.png 
          back_color: 00 