libraries:
  Movies:
    overlay_files:
      # Resolution in the upper left corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/resolution.yml

      # Audio in the upper left corner besides resolution
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/audio_codec.yml

      # Ribbons in the bottom right corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/ribbon.yml
        template_variables: 
          use_Rotten: false

      # Status in the top left corner
      - url: https://raw.githubusercontent.com/s0len/meta-manager-config/main/overlays/status.yml
